language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '11'
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'SL64YcfVIF9hz9+JxJULKCpRZBUbAxZ++aT5eKzcG8NS4bnV33TW19Csv/rlT82K32a1b21fHFWrCUYu8mldzrqzM0jKZzgcEk1j/VcXx0m5u6l4u9LE2i/tb5zRsj4Njtaek0r8aOizKme+T7Mx7k4uecZe8oOalHelGauMObTi0EkwtS5d1iOpS3D873mBt8BaS6yCwUW29ONCqnnUU2IRuW3cBMcqoNHlCIU/ZCevV3XLdNdhkiXkEyI2jFxsGJ+JU3whlwVhiQABr01ljw/uYlQB498EOU7fydWLlm5UWlbdHMbz5Fm6nDWw7bdU0ZVlBbW+KxxMRLljvY25hFNOO/0PBIrEWwujvai9xDillVqJZsHcwAS7V+an1ZB47DDBEd0TLke/vAJBrEI3RyRRZpWdvoc/u52u8qjLH3pWBB9UnusfSxg9hFz+kTS8ncFhMTC/88xOsk/r2GEl1rW885RF1HwH7jTY0rvGef/+A/Cps+fT6lNN/TvsQEqKq4rRTxP9XJPDRS4x28F+R1As0lVkiNK9X6GwQLcTPXvruAYB91LHJyXZgVgOuFiJ3SXjz7Rj3hdj87hxIig0fiU985xpxK5dBbG6Tk3GrUqx0M9+CNfa9n0C8t2678jGo8jwQrE7D4Bumju8q/Bwrn7T1k/mXPAYsJ6JjFSTAfg='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
